flutter build changes for telephony

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -30,6 +30,20 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
       
+            - name: Patch telephony plugin namespace
+        run: |
+          TELEPHONY_GRADLE="$HOME/.pub-cache/hosted/pub.dev/telephony-0.2.0/android/build.gradle"
+
+          echo "Looking for telephony build.gradle..."
+          if [ -f "$TELEPHONY_GRADLE" ]; then
+            echo "Found. Injecting namespace..."
+            sed -i '/android {/a\    namespace "com.shounakmulay.telephony"' "$TELEPHONY_GRADLE"
+          else
+            echo "telephony build.gradle not found!"
+            exit 1
+          fi
+
+      
       - name: Clean Flutter build
         run: flutter clean
 
